import { AgentHealth, type LocalOpenAiCompatibleRunnerConfig, type LocalRunnerAuthMode, type LocalRunnerKind } from "@mcoda/shared";
import { AdapterConfig, AgentAdapter, InvocationRequest, InvocationResult } from "../AdapterTypes.js";
type OpenAiConfig = AdapterConfig & {
    baseUrl?: string;
    endpoint?: string;
    apiBaseUrl?: string;
    headers?: Record<string, string>;
    temperature?: number;
    extraBody?: Record<string, unknown>;
    localRunner?: LocalOpenAiCompatibleRunnerConfig;
    runnerKind?: LocalRunnerKind;
    authMode?: LocalRunnerAuthMode;
    dummyBearerToken?: string;
    responseFormatStrategy?: string;
    healthPath?: string;
    modelsPath?: string;
    requireModelInRequest?: boolean;
    supportsStreaming?: boolean;
    supportsTools?: boolean;
    supportsJsonSchema?: boolean;
    supportsGbnf?: boolean;
};
export declare class OpenAiAdapter implements AgentAdapter {
    private config;
    private baseUrl;
    private headers;
    private temperature;
    private extraBody;
    private runnerKind;
    private authMode;
    private dummyBearerToken;
    private healthPath;
    private modelsPath;
    private localConfigIssues;
    private isLocalOpenAiCompatible;
    constructor(config: OpenAiConfig);
    getCapabilities(): Promise<string[]>;
    healthCheck(): Promise<AgentHealth>;
    invoke(request: InvocationRequest): Promise<InvocationResult>;
    invokeStream(request: InvocationRequest): AsyncGenerator<InvocationResult, void, unknown>;
    private assertConfig;
    private ensureBaseUrl;
    private ensureModel;
    private resolveAuth;
    private buildHeaders;
    private buildBody;
    private buildHealthCheckBody;
    private healthCheckLocal;
    private buildHealthResult;
    private fetchHealthPath;
    private fetchModels;
    private fetchChatProbe;
    private fetchJsonProbe;
    private resolveRunnerUrl;
    private resolveModelListUrls;
    private extractModelIds;
    private summarizeProbe;
    private summarizeModelListing;
}
export {};
//# sourceMappingURL=OpenAiAdapter.d.ts.map